<?php

// TODO : create a hook_fieldcheck that works for all modules

// TODO : add #element_validate in a hook_form_alter or someething



function fieldcheck_menu() {
  $items['form'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fieldcheck_form'),
    'access arguments' => array('access content'),
  );
  return $items;
}

function fieldcheck_form() {
  $form['test'] = array(
    '#type' => 'textfield',
    '#title' => 'test me',
    '#attributes' => array(
      'validators' => array('required', 'number'),
    ),
  );
  $form['test2'] = array(
    '#type' => 'textfield',
    '#title' => 'test me 2',
    '#attributes' => array(
      'validators' => array('required'),
    ),
  );
  return $form;
}